// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771

package icons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Settings() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"h-6 w-6 text-primary\"><line x1=\"4\" x2=\"4\" y1=\"21\" y2=\"14\"></line> <line x1=\"4\" x2=\"4\" y1=\"10\" y2=\"3\"></line> <line x1=\"12\" x2=\"12\" y1=\"21\" y2=\"12\"></line> <line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"3\"></line> <line x1=\"20\" x2=\"20\" y1=\"21\" y2=\"16\"></line> <line x1=\"20\" x2=\"20\" y1=\"12\" y2=\"3\"></line> <line x1=\"2\" x2=\"6\" y1=\"14\" y2=\"14\"></line> <line x1=\"10\" x2=\"14\" y1=\"8\" y2=\"8\"></line> <line x1=\"18\" x2=\"22\" y1=\"16\" y2=\"16\"></line></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
